




'''
本文件用于存放以及调用背部函数
分为：dict_back和array_back
dict_back:存放名称和函数本体
array_back:调用函数，显示和消除某个函数点
'''

from acupoint_back import *

'''
dict_back = {
    
    '大椎': dazhui(),
    '陶道': taodao(),
    '身柱': shenzhu(),
    '神道': shendao(),
    '灵台': lingtai(),
    '至阳': zhiyang(),
    '筋缩': jinsuo(),
    '中枢': zhongshu(),
    '脊中': jizhong(),
    '悬枢': xuanshu(),
    '命门': mingmen(),
    '腰阳关': yaoyangguan(),
    '腰俞': yaoshu(),
    '长强': changqiang(),
    
    '大抒': dashu(),
    '风门': fengmen(),
    '肺俞': feiyu(),
    '厥阴俞': jueyinyu(),
    '心俞': xinyu(),
    '督俞': duyu(),
    '膈俞': geyu(),
    '肝俞': ganyu(),
    '胆俞': danyu(),
    '脾俞': piyu(),
    '胃俞': weiyu(),
    '三焦俞': sanjiaoyu(),
    '肾俞': shenyu(),
    '气海俞': qihaiyu(),
    '大肠俞': dachangyu(),
    '关元俞': guanyuanyu(),
    '小肠俞': xiaochangyu(),
    '膀胱俞': pangguangyu(),
    '中膂俞': zhonglvyu(),
    '白环俞': baihuanyu(),
    '上髎': shangliao(),
    '次髎': ciliao(),
    '中髎': zhongliao(),
    '下髎': xialiaoxue(),
    '会阳': huiyang(),
    '附分': fufen(),
    '魄户': pohu(),
    '膏肓': gaohuang(),
    '神堂': shentang(),
    '譩譆': yixi(),
    '膈关': geguan(),
    '魂门': hunmen(),
    '阳纲': yanggang(),
    '意舍': yishe(),
    '胃仓': weicang(),
    '肓门': huangmen(),
    '志室': zhishi(),
    '胞盲': baomang(),
    '秩边': zhibian(),

    
    '承扶': chengfu(),
    '殷门': yinmen(),
    '浮郄': fuxi(),
    '委中': weizhong(),
    '委阳': weiyang(),
    '合阳': heyang(),
    '承筋': chengjin(),
    '承山': chengshan(),
    '十七椎': shiqizhui(),
    '下极俞': xiajiyu(),
    '接脊': jieji(),
    '胃脘下俞': weiwanxiashu(),
    '腰奇': yaoqi(),
    
    '肘尖': zhoujian(),
    '臑会': naohui(),
    '消泺': xiaoluo(),
    '清冷渊': qinglengyuan(),
    '天井': tianjing(),
    '四渎': sidu(),
    '三阳络': sanyangluo(),
    '支沟': zhigou(),
    '外关': waiguan(),
    '会宗': huizong(),
    '阳池': yangchi(),





    '大抒1': dashu1(),
    '风门1': fengmen1(),
    '肺俞1': feiyu1(),
    '厥阴俞1': jueyinyu1(),
    '心俞1': xinyu1(),
    '督俞1': duyu1(),
    '膈俞1': geyu1(),
    '肝俞1': ganyu1(),
    '胆俞1': danyu1(),
    '脾俞1': piyu1(),
    '胃俞1': weiyu1(),
    '三焦俞1': sanjiaoyu1(),
    '肾俞1': shenyu1(),
    '气海俞1': qihaiyu1(),
    '大肠俞1': dachangyu1(),
    '关元俞1': guanyuanyu1(),
    '小肠俞1': xiaochangyu1(),
    '膀胱俞1': pangguangyu1(),
    '中膂俞1': zhonglvyu1(),
    '白环俞1': baihuanyu1(),
    '上髎1': shangliao1(),
    '次髎1': ciliao1(),
    '中髎1': zhongliao1(),
    '下髎1': xialiaoxue1(),

    '附分1': fufen1(),
    '魄户1': pohu1(),
    '膏肓1': gaohuang1(),
    '神堂1': shentang1(),
    '譩譆1': yixi1(),
    '膈关1': geguan1(),
    '魂门1': hunmen1(),
    '阳纲1': yanggang1(),
    '意舍1': yishe1(),
    '胃仓1': weicang1(),
    '肓门1': huangmen1(),
    '志室1': zhishi1(),
    '胞盲1': baomang1(),
    '秩边1': zhibian1(),

    '胃脘下俞1': weiwanxiashu1(),


    '肘尖1': zhoujian1(),
    '臑会1': naohui1(),
    '消泺1': xiaoluo1(),
    '清冷渊1': qinglengyuan1(),
    '天井1': tianjing1(),
    '四渎1': sidu1(),
    '三阳络1': sanyangluo1(),
    '支沟1': zhigou1(),
    '外关1': waiguan1(),
    '会宗1': huizong1(),
    '阳池1': yangchi1(),

    '承扶1': chengfu1(),
    '殷门1': yinmen1(),
    '浮郄1': fuxi1(),
    '委中1': weizhong1(),
    '委阳1': weiyang1(),
    '合阳1': heyang1(),
    '承筋1': chengjin1(),
    '承山1': chengshan1(),


}

'''在array里面选择函数名称，要选择某一个，删去其前面的
array_back = [

    '大椎',
    '陶道',
    '身柱',
    '神道',
    '灵台',
    '至阳',
    '筋缩',
    '中枢',
    '脊中',
    '悬枢',
    '命门',
    '腰阳关',
    '腰俞',
    '长强',

    '风门',
    '肺俞',
    '厥阴俞',
    '心俞',
    '督俞',
    '膈俞',
    '肝俞',
    '胆俞',
    '脾俞',
    '胃俞',
    '三焦俞',
    '肾俞',
    '气海俞',
    '大肠俞',
    '关元俞',
    '小肠俞',
    '膀胱俞',
    '中膂俞',
    '白环俞',
    '上髎',
    '次髎',
    '中髎',
    '下髎',
    '会阳',
    '附分',
    '魄户',
    '膏肓',
    '神堂',
    '譩譆',
    '膈关',
    '魂门',
    '阳纲',
    '意舍',
    '胃仓',
    '肓门',
    '志室',
    '胞盲',
    '秩边',

    '承扶',
    '殷门',
    '浮郄',
    '委中',
    '委阳',
    '合阳',
    '承筋',
    '承山',
    '十七椎',
    '下极俞',
    '接脊',
    '大抒',
    '胃脘下俞',
    '肘尖',

    '肘尖1',
    '臑会',
    '消泺',
    '清冷渊',
    '天井',
    '四渎',
    '三阳络',
    '支沟',
    '外关',
    '会宗',
    '阳池',


    '大抒1',
    '风门1',
    '肺俞1',
    '厥阴俞1',
    '心俞1',
    '督俞1',
    '膈俞1',
    '肝俞1',
    '胆俞1',
    '脾俞1',
    '胃俞1',
    '三焦俞1',
    '肾俞1',
    '气海俞1',
    '大肠俞1',
    '关元俞1',
    '小肠俞1',
    '膀胱俞1',
    '中膂俞1',
    '白环俞1',
    '上髎1',
    '次髎1',
    '中髎1',
    '下髎1',


    '附分1',
    '魄户1',
    '膏肓1',
    '神堂1',
    '譩譆1',
    '膈关1',
    '魂门1',
    '阳纲1',
    '意舍1',
    '胃仓1',
    '肓门1',
    '志室1',
    '胞盲1',
    '秩边1',

    '臑会1',
    '消泺1',
    '清冷渊1',
    '天井1',
    '四渎1',
    '三阳络1',
    '支沟1',
    '外关1',
    '会宗1',
    '阳池1',

    '承扶1',
    '殷门1',
    '浮郄1',
    '委中1',
    '委阳1',
    '合阳1',
    '承筋1',
    '承山1',
    '胃脘下俞1',
]

back_name = []
for key in array_back:
    back_name.append(dict_back[key])
