




'''
本文件用于存放以及调用背部函数
分为：dict_front和array_front
dict_front:存放名称和函数本体
array_front:调用函数，显示和消除某个函数点
'''

from acupoint_front import *

'''

dict_front = {
    '曲骨': qugu(),
    '中极': zhongji(),
    '关元': guanyuan(),
    '石门': shimen(),
    '气海': qihai(),
    '阴交': yinjiao(),
    '肚脐': duqi(),
    '水分': shuifen(),
    '下脘': xiawan(),
    '建里': jianli(),
    '中脘': zhongwan(),
    '上脘': shangwan(),
    '巨阙': juque(),
    '鸠尾': jiuwei(),
    '中庭': zhongting(),
    '谭中': tanzhong(),
    '玉堂': yutang(),
    '紫宫': zigong(),
    '华盖': huagai(),
    '璇玑': xuanji(),
    '天突': tiantu(),
    
    '横骨': henggu(),
    '大赫': dahe(),
    '气穴': qixue(),
    '四满': siman(),
    '中注': zhongzhu(),
    '肓俞': huangshu(),
    '商曲': shangqu(),
    '石关': shiguan(),
    '阴都': yindu(),
    '腹通谷': futonggu(),
    '幽门': youmen(),
    '步廊': bulang(),
    '神封': shenfeng(),
    '灵虚': lingxu(),
    '神藏': shenzang(),
    '彧中': yuzhong(),
    
    '气冲': qichong(),
    '归来': guilai(),
    '水道': shuidao(),
    '大巨': daju(),
    '外陵': wailing(),
    '天枢': tianshu(),
    '滑肉门': huaroumen(),
    '太乙': taiyi(),
    '关门': guanmen(),
    '梁门': liangmen(),
    '承满': chengman(),
    '不容': burong(),
    '乳根': rugen(),
    '乳中': ruzhong(),
    '膺窗': yingchuang(),
    '屋翳': wuyi(),
    '库房': kufang(),
    '气户': qihu(),
    
    '髀关': biguan(),
    '伏兔': futu(),
    '阴市': yinshi(),
    '梁丘': liangqiu(),
    '犊鼻': dubi(),
    '足三里': zusanli(),
    '上巨虚': shangjuxu(),
    '条口': tiaokou(),
    '下巨虚': xiajuxu(),
    '丰隆': fenglong(),
    '解溪': jiexi(),
    
    '冲门': chongmen(),
    '腹结': fujie(),
    '大横穴': daheng(),
    '腹哀': fuai(),
    '食窦': shidou(),
    '天溪': tianxi(),
    '胸乡': xiongxiang(),
    '周荣': zhourong(),
    
    '天池': tianchi(),
    '天泉': tianquan(),
    '左曲泽': left_quze(),
    '郄门': ximen(),
    '间使': jianshi(),
    '内关': neiguanxue(),
    '大陵': dalin(),
    '左少海': left_shaohai(),
    '灵道': lingdao(),
    '通里': tongli(),
    '阴郄': yinxi(),
    '神门': shenmen(),
    '天府': tianfu(),
    '侠白穴': xiabai(),
    '尺泽': chize(),
    '孔最': kongzui(),
    '列缺': lieque(),
    '太渊': taiyuan(),
    '急脉': jimai(),
    '阴廉': yinglian(),
    '足五里': zuwuli(),
    '血海': xuehai(),
    '右腕': youwan(),
    '经渠': jingqu(),
    '俞府': yufu(),
    '会阴': huiyin(),
    '膝眼1': xiya1(),
    '膝眼2': xiya2(),
    '鹤顶': heding(),
    '髋骨1': kuangu1(),
    '髋骨2': kuangu2(),
    '阑尾': lanwei(),
    '百虫窝': baichongwo(),
    '箕门': jimen(),
    
    '三角灸1': sanjiaojiu1(),
    '三角灸2': sanjiaojiu2(),
    '利尿': liniao(),
    '子宫': dome(),



    
    '横骨1': henggu1(),
    '大赫1': dahe1(),
    '气穴1': qixue1(),
    '四满1': siman1(),
    '中注1': zhongzhu1(),
    '肓俞1': huangshu1(),
    '商曲1': shangqu1(),
    '石关1': shiguan1(),
    '阴都1': yindu1(),
    '腹通谷1': futonggu1(),
    '幽门1': youmen1(),
    '步廊1': bulang1(),
    '神封1': shenfeng1(),
    '灵虚1': lingxu1(),
    '神藏1': shenzang1(),
    '彧中1': yuzhong1(),
    
    '气冲1': qichong1(),
    '归来1': guilai1(),
    '水道1': shuidao1(),
    '大巨1': daju1(),
    '外陵1': wailing1(),
    '天枢1': tianshu1(),
    '滑肉门1': huaroumen1(),
    '太乙1': taiyi1(),
    '关门1': guanmen1(),
    '梁门1': liangmen1(),
    '承满1': chengman1(),
    '不容1': burong1(),
    '乳根1': rugen1(),
    '乳中1': ruzhong1(),
    '膺窗1': yingchuang1(),
    '屋翳1': wuyi1(),
    '库房1': kufang1(),
    '气户1': qihu1(),
    
    '冲门1': chongmen1(),
    '腹结1': fujie1(),
    '大横穴1': daheng1(),
    '腹哀1': fuai1(),
    '食窦1': shidou1(),
    '天溪1': tianxi1(),
    '胸乡1': xiongxiang1(),
    '周荣1': zhourong1(),
    '利尿1': liniao1(),
    '子宫1': dome1(),




    '髀关1': biguan1(),
    '伏兔1': futu1(),
    '阴市1': yinshi1(),
    '梁丘1': liangqiu1(),
    '犊鼻1': dubi1(),
    '足三里1': zusanli1(),
    '上巨虚1': shangjuxu1(),
    '条口1': tiaokou1(),
    '下巨虚1': xiajuxu1(),
    '丰隆1': fenglong1(),
    '解溪1': jiexi1(),

    
    '天池1': tianchi1(),
    '天泉1': tianquan1(),
    '左曲泽1': left_quze1(),
    '郄门1': ximen1(),
    '间使1': jianshi1(),
    '内关1': neiguanxue1(),
    '大陵1': dalin1(),
    '左少海1': left_shaohai1(),
    '灵道1': lingdao1(),
    '通里1': tongli1(),
    '阴郄1': yinxi1(),
    '神门1': shenmen1(),
    '天府1': tianfu1(),
    '侠白穴1': xiabai1(),
    '尺泽1': chize1(),
    '孔最1': kongzui1(),
    '列缺1': lieque1(),
    '太渊1': taiyuan1(),
    '急脉1': jimai1(),
    '阴廉1': yinglian1(),
    '足五里1': zuwuli1(),
    '血海1': xuehai1(),
    '右腕1': youwan1(),
    '经渠1': jingqu1(),
    '俞府1': yufu1(),
    '膝眼11': xiya11(),
    '膝眼21': xiya21(),
    '鹤顶1': heding1(),
    '髋骨11': kuangu11(),
    '髋骨21': kuangu21(),
    '阑尾1': lanwei1(),
    '百虫窝1': baichongwo1(),
    '箕门1': jimen1(),

}

'''在array里面选择函数名称，要选择某一个，删去其前面的
array_front = [


    '曲骨',
    '中极',
    '关元',
    '石门',
    '气海',
    '阴交',
    '肚脐',
    '水分',
    '下脘',
    '建里',
    '中脘',
    '上脘',
    '巨阙',
    '鸠尾',
    '中庭',
    '谭中',
    '玉堂',
    '紫宫',
    '华盖',
    '璇玑',
    '天突',

    '横骨',
    '大赫',
    '气穴',
    '四满',
    '中注',
    '肓俞',
    '商曲',
    '石关',
    '阴都',
    '腹通谷',
    '幽门',
    '步廊',
    '神封',
    '灵虚',
    '神藏',
    '彧中',

    '气冲',
    '归来',
    '水道',
    '大巨',
    '外陵',
    '天枢',
    '滑肉门',
    '太乙',
    '关门',
    '梁门',
    '承满',
    '不容',
    '乳根',
    '乳中',
    '膺窗',
    '屋翳',
    '库房',
    '气户',

    '髀关',
    '伏兔',
    '阴市',
    '梁丘',
    '犊鼻',
    '足三里',
    '上巨虚',
    '条口',
    '下巨虚',
    '丰隆',
    '解溪',

    '冲门',
    '腹结',
    '大横穴',
    '腹哀',
    '食窦',
    '天溪',
    '胸乡',
    '周荣',

    '天池',
    '天泉',
    '左曲泽',
    '郄门',
    '间使',
    '内关',
    '大陵',

    '左少海',
    '灵道',
    '通里',
    '阴郄',
    '神门',

    '天府',
    '侠白穴',
    '尺泽',
    '孔最',
    '列缺',
    '太渊',

    '急脉',
    '阴廉',
    '足五里',
    '血海',


    '经渠',
    '俞府',
    '会阴',
    '膝眼1',
    '膝眼2',
    '鹤顶',
    '髋骨1',
    '髋骨2',
    '阑尾',
    '百虫窝',
    '箕门',
    '三角灸1',
    '三角灸2',
    '利尿',
    '子宫',




    '横骨1',
    '大赫1',
    '气穴1',
    '四满1',
    '中注1',
    '肓俞1',
    '商曲1',
    '石关1',
    '阴都1',
    '腹通谷1',
    '幽门1',
    '步廊1',
    '神封1',
    '灵虚1',
    '神藏1',
    '彧中1',

    '气冲1',
    '归来1',
    '水道1',
    '大巨1',
    '外陵1',
    '天枢1',
    '滑肉门1',
    '太乙1',
    '关门1',
    '梁门1',
    '承满1',
    '不容1',
    '乳根1',
    '乳中1',
    '膺窗1',
    '屋翳1',
    '库房1',
    '气户1',

    '冲门1',
    '腹结1',
    '大横穴1',
    '腹哀1',
    '食窦1',
    '天溪1',
    '胸乡1',
    '周荣1',
    '利尿1',
    '子宫1',
    '髀关1',
    '伏兔1',
    '阴市1',
    '梁丘1',
    '犊鼻1',
    '足三里1',
    '上巨虚1',
    '条口1',
    '下巨虚1',
    '丰隆1',
    '解溪1',

    '天池1',
    '天泉1',
    '左曲泽1',
    '郄门1',
    '间使1',
    '内关1',
    '大陵1',
    '左少海1',
    '灵道1',
    '通里1',
    '阴郄1',
    '神门1',
    '天府1',
    '侠白穴1',
    '尺泽1',
    '孔最1',
    '列缺1',
    '太渊1',
    '急脉1',
    '阴廉1',
    '足五里1',
    '血海1',
    '经渠1',
    '俞府1',
    '膝眼11',
    '膝眼21',
    '鹤顶1',
    '髋骨11',
    '髋骨21',
    '阑尾1',
    '百虫窝1',
    '箕门1'


]

front_name = []
for key in array_front:
    front_name.append(dict_front[key])
